### ISSUE TITLE
Kits!

### ISSUE THREAD

**Issue by daniktheboss** [PEMapModder/HereAuth#68] opened 2016-09-30 20:22 UTC
When u get a kit u receive only first item. Relogin and you get all the kit items!

**Comment by robske110** [comment] 2016-09-30 20:34
err, this is very not well expressed.
i don't think this plugin has to do anything with kits.
it has to do sth with inventory though...

**Comment by daniktheboss** [comment] 2016-09-30 20:48
Ok. I use blank server and install kit plugin. I get a kit and receive all the items. I install hereauth and kit plugin and get the kit but only get one of the items.

**Comment by SOF3** [comment] 2016-10-01 04:51
Please provide full steps to reproduce this issue.

**Comment by ghost** [comment] 2016-10-11 15:44
@daniktheboss  i dont have that problem i have kit pvp i get my kits on first spawn zo

close it

**Comment by ghost** [comment] 2016-10-11 15:46
but i test it with latest build mayby dont close it maybe kits plugin bugg

**Comment by SOF3** [comment] 2016-10-11 16:36
This issue will be reopened if full steps to reproduce the issue are provided.

**Closed as completed by SOF3** 2016-10-11 16:36 UTC

**Comment by daniktheboss** [comment] 2016-10-11 23:14
1. Download hereauth 
2. Download any kit plugin
3. Join in server, login and pick any kit.
4. You will only get one item of the kits (in your hotbar only first item.)
5. Rejoin server and you will get all items.
   Ex: kit has 1 sword and apple, you pick kit you will get only the sword. Relogin and you will get the apples

**Comment by ghost** [comment] 2016-10-12 05:04
I f dont have it

**Comment by ghost** [comment] 2016-10-12 05:05
@daniktheboss i dont have it i use serverkits from pmmp forums

**Comment by SOF3** [comment] 2016-10-12 08:18
@daniktheboss "Download any kit plugin" is not precise enough. You should specify one, because "any kit plugin" can refer to any plugin that calls itself kit plugin.

**Comment by daniktheboss** [comment] 2016-10-12 10:27
Kidding me? Whatever I stopped using hereauth cus of this.
