### ISSUE TITLE
How to port SimpleAuth data to HereAuth?

### ISSUE THREAD

**Issue by XiangZhao969** [PEMapModder/HereAuth#24] opened 2016-02-12 15:40 UTC

**Comment by PEMapModder** [comment] 2016-02-12 15:53
This is being worked on. Duplicate of #1

**Comment by PEMapModder** [comment] 2016-02-12 15:54
Actually, there are already the basic scripts for them. Written input, still haven't written output.

If you are using MySQL, however, it would be a lot easier.

**Closed as completed by PEMapModder** 2016-02-12 15:53 UTC
Labels: duplicate

**Comment by XiangZhao969** [comment] 2016-02-12 15:56
Could you tell me how to do that, i'm so noob at this

**Comment by PEMapModder** [comment] 2016-02-12 17:19
This is being worked on. It is just awkward to let you properly specify the paths of the input and output directories.

Please refer to #1 in the future.
