### ISSUE TITLE
Some advice.

### ISSUE THREAD

**Issue by jerryzooyoyo** [PEMapModder/HereAuth#43] opened 2016-04-02 12:49 UTC
- [x] All messages translatable ( There are some messages untranslatable now )
- [x] Add option that let player join ONLY ONE ACCOUNT. ( using Client ID I think )

Great plugin you did. Keep updating =)

**Comment by robske110** [comment] 2016-04-02 12:53
That only one account is quite hard
this would result into:
Either-you can only use 1 account per device. BAD. (You could not log on Player3635 with two different devices.)
Or-if a player logs on with an already registered account he won't be able to log in with another
And-what's the sense of that? Modify alias to use clientIDs?

**Comment by PEMapModder** [comment] 2016-04-02 13:00
Yes, there is an option about Accounts per IP. https://github.com/PEMapModder/HereAuth/blob/master/resources/config.yml#L211

**Comment by PEMapModder** [comment] 2016-04-02 13:00
The first one is duplicate of #42.

**Closed as completed by PEMapModder** 2016-04-02 13:00 UTC

**Comment by jerryzooyoyo** [comment] 2016-04-02 13:02
Well, because in my server, players will just keep creating new account, and get lots of new-player-kits.
This is pretty annoying. So using one account per device may be good.
Any way, just an option. Not a must one.

**Comment by jerryzooyoyo** [comment] 2016-04-02 13:02
@robske110 Well, because in my server, players will just keep creating new account, and get lots of new-player-kits.
This is pretty annoying. So using one account per device may be good.
Any way, just an option. Not a must one.

**Comment by PEMapModder** [comment] 2016-04-02 13:03
@jerryzooyoyo default settings is three accounts per IP. Isn't it working now?

**Comment by jerryzooyoyo** [comment] 2016-04-02 13:07
@PEMapModder Well, in my country, a player might have different IPs in different areas. And if I enable the option that let three accounts per IP, it might take its toll on many public Wi-Fis.

**Comment by jerryzooyoyo** [comment] 2016-04-02 13:09
@PEMapModder For example, one player named XXX may using different WI-FIs to join, then he will have a chance to have more than 1 account.

**Comment by PEMapModder** [comment] 2016-04-02 13:34
IP is already the most reliable method to identify a player. Other methods can be changed by the player himself.

**Comment by robske110** [comment] 2016-04-02 13:35
Client ID is changeable in:
Android
Win10
Jailbreak::iOS
so 95% of all devices

**Comment by PEMapModder** [comment] 2016-04-02 13:41
@jerryzooyoyo My advice is, ask the plugin developer of your kit plugin to give kits only when the player has been online for more than a total of 24 hours, etc.

**Comment by jerryzooyoyo** [comment] 2016-04-02 13:51
@PEMapModder Ok.I will ask him. Thanks for your help.=)
